# Generated by Django 5.0.6 on 2024-09-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_amount_remove_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
    ]
