# Generated by Django 5.0.6 on 2024-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_delete_bankaccount_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='account',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='AccountVerification',
        ),
    ]
