# Generated by Django 5.0.6 on 2024-10-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_remove_account_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_payment_verified",
            field=models.BooleanField(default=False),
        ),
    ]
