# Generated by Django 5.0.6 on 2024-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_account_is_payment_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_holder',
            field=models.CharField(default='', max_length=100),
        ),
    ]
