# Generated by Django 5.0.6 on 2024-11-24 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_rename_acceptance_intent_conversation_is_acceptance_intent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_acceptance_intent',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_transfer_intent',
        ),
        migrations.AddField(
            model_name='conversation',
            name='transaction_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='transferee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferee_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
