# Generated by Django 5.0.6 on 2024-12-31 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        ('tickets', '0024_remove_ticket_status_ticket_istransfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='ticket_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_ticket_2', to='tickets.ticket'),
        ),
    ]
