# Generated by Django 5.0.6 on 2025-01-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_exchange_ticket_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='difference_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='pay_direction',
            field=models.CharField(blank=True, choices=[('buyerToSeller', 'Buyer to Seller'), ('sellerToBuyer', 'Seller to Buyer'), ('none', 'None')], default='none', max_length=20, null=True),
        ),
    ]
