# Generated by Django 5.0.6 on 2024-09-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_social_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profilepic_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remaining_points',
            field=models.IntegerField(default=0),
        ),
    ]
