# Generated by Django 5.0.6 on 2024-09-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_is_social_login_userprofile_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kakao_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
