# Generated by Django 5.0.6 on 2024-09-23 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_bankaccount_user_and_more'),
        ('user', '0005_userprofile_kakao_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.account'),
        ),
    ]
