# Generated by Django 5.0.6 on 2024-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userprofile_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='remaining_points',
        ),
    ]
