# Generated by Django 5.0.6 on 2024-10-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userprofile_bank_name_alter_userprofile_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_payment_verified',
            field=models.BooleanField(default=True),
        ),
    ]
