# Generated by Django 5.0.6 on 2024-10-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_userprofile_is_payment_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bank_account",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_payment_verified",
        ),
    ]
