# Generated by Django 5.0.6 on 2024-11-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_userprofile_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
