# Generated by Django 5.0.6 on 2024-09-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferhistory',
            name='chat_room',
        ),
    ]
