# Generated by Django 5.0.6 on 2024-09-23 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, default='No description available', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Untitled Ticket', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_details',
            field=models.CharField(default='No discounts applied', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='casting',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(default='General Admission', max_length=50),
        ),
    ]
