# Generated by Django 5.0.6 on 2024-09-23 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_bankaccount_user_and_more'),
        ('tickets', '0005_remove_ticket_file_upload_ticket_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrequest',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('transfer_pending', '양도 중'), ('transfer_completed', '양도 완료'), ('received_completed', '양수 완료')], default='transfer_pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transferee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_transferee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TransferHistory',
        ),
        migrations.DeleteModel(
            name='TransferRequest',
        ),
    ]
