# Generated by Django 5.0.6 on 2024-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_transferrequest_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.AddField(
            model_name='ticket',
            name='masked_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/masked/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='processed_seat_image',
            field=models.FileField(blank=True, null=True, upload_to='tickets/seats/processed/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='uploaded_seat_image',
            field=models.FileField(blank=True, null=True, upload_to='tickets/seats/'),
        ),
    ]
