# Generated by Django 5.0.6 on 2024-10-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_id_ticketpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone_last_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('transfer_pending', '양도 중'), ('transfer_completed', '양도 완료')], default='transfer_pending', max_length=20),
        ),
    ]
