# Generated by Django 5.0.6 on 2024-10-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_phone_last_digits_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='keyword',
            field=models.CharField(default='인터파크', max_length=100),
        ),
    ]
