# Generated by Django 5.0.6 on 2024-10-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='masked_file',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('waiting', '양수자 대기'), ('transfer_pending', '양도 중'), ('transfer_completed', '양도 완료')], default='transfer_pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uploaded_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
