# Generated by Django 5.0.6 on 2024-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_ticket_masked_file_alter_ticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='masked_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/masked/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
