# Generated by Django 5.0.6 on 2024-10-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_masked_file_alter_ticket_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking_details',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='masked_file',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='processed_seat_image',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='transferee',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='casting',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_last_digits',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uploaded_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uploaded_seat_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
