# Generated by Django 5.0.6 on 2024-10-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_remove_ticket_phone_last_digits_ticket_masked_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone_last_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
