# Generated by Django 5.0.6 on 2024-11-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_ticket_phone_last_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('waiting', '양수자 대기'), ('transfer_pending', '양도 중'), ('transfer_completed', '양도 완료')], default='waiting', max_length=20),
        ),
    ]
