# Generated by Django 5.0.6 on 2024-11-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_page',
            field=models.CharField(default='인터파크', max_length=255),
        ),
    ]
