# Generated by Django 5.0.6 on 2024-11-30 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_ticket_booking_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpost',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticketpost',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tickets.ticket'),
        ),
    ]
