# Generated by Django 5.0.6 on 2024-12-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_remove_ticketpost_id_alter_ticketpost_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='keyword',
        ),
    ]
